steps:
  e2e:
    # this image must be the same as in `scripts/e2e.sh`
    image: mcr.microsoft.com/playwright:v1.42.1-jammy
    commands:
      - npm ci
      - npx playwright test
when:
  event:
    - pull_request
