steps:
  install:
    image: codeberg.org/woodpecker-plugins/node-pm
    commands:
      - pnpm i --frozen-lockfile
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/ember-rdfa-editor
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  ref: refs/tags/v*
