steps:
  changelog:
    image: danlynn/ember-cli:4.8.0
    commands:
      - git fetch origin master
      - git diff -wb --name-only origin/master..HEAD | grep CHANGELOG.md
  install:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:4.8.0
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:4.8.0
    group: lint
    commands:
      - npm run lint:hbs
  test:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm run test:ember
  precompile:
    image: danlynn/ember-cli:4.8.0
    commands:
      - ember ts:precompile
when:
  event:
    - pull_request
