name: 'pull-request'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled


jobs:
  changelog:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPENDABOT_TOKEN }}

      - name: Update the changelog
        uses: abeforgit/dependabot-changelog-helper@6ac73689e40c543f6b802f4c72b9c4f66053adf5
        with:
          activationLabel: 'dependabot'
          changelogPath: './CHANGELOG.md'

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update changelog"
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'


 

